### ISSUE TITLE
buildbot

### ISSUE THREAD

**Issue by udeved** [artix-linux/artix#1]
@aadityabagga 

How would you approach the branches in this repo to autobuild?
The set of packages should be equal to arch-openrc plus more eventually.

**Comment by aadityabagga** [comment]
Hi @udeved,

The travis build bot can build branches, just the code needs to be added. If each branch needs to be a separate output repo, that can be done as well.

**Comment by udeved** [comment]
@aadityabagga 

My plan was merging like this

```
system-overlay 
     |----------------> system-testing(repo?) ----------------> system(repo)  
system-openrc
```

Same for the other two, world and galaxy branches.
So if travis could build say the merges into system-testing, we could slowly complete the system repo to have a full set and not rely on arch for the basic stuff.
My goal would be to have at least the full core/system repo in place, but can only be maintained with buildbot and some help.

**Comment by aadityabagga** [comment]
Ah, I see the plan now. Yup, it could work, provided the package no per merge is not too high.

I have been looking into using the [caching feature](https://docs.travis-ci.com/user/caching/) of travis-ci, doing so could speed up our initial bootstrap phase and if it works we could also store the built packages and check them before building; this way we could retry builds that take long time so that eventually all packages in a commit / merge can get built (of course if a single package compiles for more than 50 min it would not work).

Will add the buildbot code and try to implement caching part. Will let you know after creating initial pull request and if you can help with missing parts it would speed up the process.

**Comment by udeved** [comment]
Sounds great. Let me know when you need help.

The idea was, we keep the script provider packages, and do their depend packages init neutral, perhaps only adding optdepends. This way, we could easily add other init support like s6 or runit. 

I guess gcc builds within 50mins with travis, not sure about kernel though, we may keep the in dedicated branches to merge, to make sure we never merge a big one with kernel and gcc for example?

**Comment by aadityabagga** [comment]
The caching of initial bootstrap did not work out, got [permission errors]((https://travis-ci.org/aadityabagga/artix/builds/251740899#L970)) when building in the rebuilt cache.

Was able to [build](https://travis-ci.org/aadityabagga/artix/builds/251755183) glibc though :-)

PR: https://github.com/cromnix/artix/pull/8
